export const EnrollmentStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PAID: "PAID",
  COMPLETED: "COMPLETED",
  DROPPED: "DROPPED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
  INACTIVE: "INACTIVE",
  ACTIVE: "ACTIVE",
};
